name: Build Static Articles

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 */6 * * *' # every 6 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql, pdo_sqlite
          coverage: none

      - name: Run build script
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        run: |
          php scripts/build_articles.php

      - name: Commit generated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit";
          else
            git commit -m "chore: generate static articles $(date -u +'%Y-%m-%dT%H:%M:%SZ')";
            git push;
          fi

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: docs
