name: Refresh Articles

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch: {}
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/refresh.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql
          coverage: none

      - name: Run build script
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
          ARTICLE_LIMIT: 5
        run: php scripts/build_articles.php

      - name: Commit updated docs (if changed)
        run: |
          if [[ -n $(git status --porcelain docs/) ]]; then
            git config user.name 'github-actions'
            git config user.email 'actions@users.noreply.github.com'
            git add docs/
            git commit -m "Automated refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
            git push
          else
            echo 'No changes to commit.'
          fi
